#!/bin/sh

# retag all "new" messages "inbox" and "unread"
notmuch tag +inbox +unread -new -- tag:new
# github notifications skip the inbox
notmuch tag -inbox +github_notification -- tag:inbox and from:notifications@github.com
notmuch tag +todo -- tag:github_notification and to:review_requested@noreply.github.com
notmuch tag +todo -- tag:inbox and from:peoplehremail.com and "Holiday Request"
# tag all messages from "me" as sent and remove tags inbox and unread
notmuch tag -new -inbox +sent -unread -- from:bob@made.com or from:bob.gregory@made.com or from:bob@codefiend.co.uk or from:pathogenix@gmail.com and tag:new
# tag newsletters, but dont show them in inbox
notmuch tag +newsletters +unread -new -- tag:inbox and from:newsletter@example.org or subject:'newsletter*'
#Rsyslog
notmuch tag +rsyslog +unread -new -inbox -- tag:inbox and subject:'[rsyslog]*'
#Noise
notmuch tag -archive +noise +payment_failed -inbox --  tag:inbox and subject:"Payment Transaction Failed"
notmuch tag -archive +noise +payment_failed -inbox --  to:f166bb-pay@made.com
notmuch tag -archive +noise -inbox --  from:support@pcapredict.com
notmuch tag -archive +noise +sitemap_failed -inbox --  tag:inbox and subject:"Sitemap generate Warnings"
notmuch tag -archive +noise +payment_failed -inbox --  tag:inbox and from:"no-reply@rentabiliweb.com"
notmuch tag -archive +noise -inbox --  tag:inbox and from:"platform@productsup.com" and subject:"Warning"
notmuch tag -archive +noise -inbox --  tag:inbox and from:"CaptureSupport@loqate.com"
notmuch tag -archive +noise -inbox --  tag:inbox and from:"no-reply@reviews.co.uk"
notmuch tag -archive +noise -inbox --  tag:inbox and from:"no-reply@okta.com" and subject:"User(s) deactivated"
notmuch tag -archive +noise -inbox --  tag:inbox and subject:"Supply Chain Scorecard"
#Accounts
notmuch tag +work -- tag:inbox and to:made.com
notmuch tag +personal -- tag:inbox and to:pathogenix@gmail.com or to:bob@codefiend.co.uk

# Alerts
notmuch tag +datadog +alert -inbox -- tag:inbox and from:alert@dtdg.co
notmuch tag +aws +alert -inbox -- tag:inbox and from:"AWS Notifications"
notmuch tag +pingdom +alert -inbox -- tag:inbox and from:alert@pingdom.com
notmuch tag +pingdom -inbox -- tag:inbox and from:no-reply@pingdom.com
notmuch tag +pagerduty +alert -- tag:inbox and from:no-reply@pagerduty.com
notmuch tag +riemann +alert -inbox -- tag:inbox and from:riemann@made.com
notmuch tag +pcapredict +alert -inbox -- tag:inbox and from support@pcapredict.com
notmuch tag +be2bill +alert -inbox -- tag:inbox and from support@be2bill.com
notmuch tag +be2bill +alert -inbox -- tag:inbox and from no-reply@dalenys.com
notmuch tag +adyen +alert -inbox -- tag:inbox and from do-not-reply@adyen.com

# Reports
notmuch tag +report -inbox -- tag:inbox and from:noreply@newrelic.com and "performance report"
notmuch tag +report -inbox -- tag:inbox and from:feedback@slack.com
notmuch tag +report -- tag:inbox and from:peoplehremail.com and "Weekly Recap"

notmuch tag -work +personal +family +school -inbox -- from:"Royal Alexandra&Albert School" and tag:inbox
notmuch tag -work +personal +family +school -inbox -- (from:warwick.surrey.sch.uk OR from:"Warwick School") and tag:inbox
notmuch tag +report -- from:Pingdom subject:"Daily Report"

# AWS
notmuch tag +aws -inbox -- tag:inbox and from:made.com and from:"Amazon Web Services"

#Cert
notmuch tag +cert -inbox +newsletter -- tag:inbox and from:ncas.us-cert.gov

# Calendar
notmuch tag +cal -- tag:inbox and mimetype:text/calendar or mimetype:application/ics
notmuch tag +cal -inbox -- tag:inbox and from:getsolid.io

# Announcements
notmuch tag +announce -inbox -- "[Housekeeping Updates]" or "[Company Announcements]" or "[New Starters, Promotions & Leavers]"
notmuch tag +fbwork -inbox -- tag:inbox and from:fbworkmail.com
notmuch tag +meetup -inbox -- tag:inbox and from:info@meetup.com
notmuch tag +meetup -inbox -- tag:inbox and from:Gartner.Events@gartner.com
notmuch tag +meetup -inbox -- tag:inbox and from:community@skillsmatter.com


# github notifications skip the inbox
notmuch tag -inbox +github_notification -- tag:new and from:notifications@github.com
# tag all messages from "me" as sent and remove tags inbox and unread
notmuch tag -new -inbox +sent -- tag:new and from:bob@codefiend.co.uk or from:pathogenix@gmail.com and tag:new
# tag newsletters, but dont show them in inbox
notmuch tag +newsletters -inbox -- tag:new and from:bill@sinocism.com or from:skeptoid.com or from:m@ttias.be or electoral-reform.org or from:MartinsMoneyTips@moneysavingexpert.com or from:team@kaggle.com or from:digest-noreply@quora.com

notmuch tag +newsletter +go -- tag:new and from:discourse@forums.online-go.com or from:news@gogameguru.com
notmuch tag +newsletters +commercial -inbox -- tag:new and from:influxdata.com
notmuch tag +newsletter +commercial -inbox -unread -- from:imperialcandles@gmail.com
notmuch tag +newsletter +commercial -- from:bbc@bbc.co.uk
notmuch tag +newsletter +commercial -- from:contact@mailer.humblebundle.com
notmuch tag +newsletter +commercial -- from:team@hired.com
notmuch tag +newsletter +commercial -- from:editor@toptal.com

# social
notmuch tag +social -inbox -unread -- tag:new and from:messages-noreply@linkedin.com or from:noreply@youtube.com or from:notifications-noreply@linkedin.com

# To-do
notmuch tag +todo -- tag:new and from:redhill.library@surreycc.gov.uk

#Accounts
notmuch tag +personal -- tag:new and to:pathogenix@gmail.com or to:bob@codefiend.co.uk

#Jobs
notmuch tag +career -inbox -- tag:new and from:do-not-reply@stackoverflow.email or from:jobs-listings@linkedin.com
notmuch tag +career -inbox -unread -- tag:new and functionalworks.com


# Receipts
notmuch tag +payments -inbox -- tag:new and from:googleplay-noreply@google.com
notmuch tag +payments -inbox -- tag:new and from:service@paypal.co.uk

# School
notmuch tag +family +wraycommon -- tag:new and from:wray-common@scopay.com
notmuch tag +family +warwick -- tag:new and from:wray-common@scopay.com

